# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - main

# pool:
# # vmImage: ubuntu-latest
#   name: Default

# # steps:
# # - script: echo Hello, world!
# #   displayName: 'Run a one-line script'

# # - script: |
# #     echo Add other tasks to build, test, and deploy your project.
# #     echo See https://aka.ms/yaml
# #   displayName: 'Run a multi-line script'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '18.x'
#   displayName: "Use Node.js 18"

# - script: |
#     npm install -g pnpm
#     cd vue-project
#     pnpm install
#     pnpm run build
#     echo "=== Contents after build ==="
#     dir
#   shell: cmd
#   displayName: "Install deps & build Vue app"


# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: 'vue-project/dist'
#     artifact: 'vue-dist'
#     publishLocation: 'pipeline'
#   displayName: "Publish Vue dist folder"

trigger:
- main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Use Node.js 18'

- script: npm install -g pnpm
  displayName: 'Install pnpm globally'

- script: |
    pnpm install
    pnpm run build --verbose
    echo "##[debug]pnpm run build finished. Checking working directory..."
    dir vue-project
  workingDirectory: vue-project
  displayName: 'Install and Build Vue app'

- script: |
    echo "Checking for the dist folder..."
    if exist vue-project\dist (
      echo "dist folder found. Proceeding with publish."
    ) else (
      echo "Error: dist folder not found."
      exit 1
    )
  displayName: 'Verify dist folder exists (Windows)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'vue-project/dist'
    artifact: 'vue-dist'
  displayName: 'Publish Vue dist folder'