# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
# vmImage: ubuntu-latest
  name: Default

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: "Use Node.js 18"

- script: |
    cd vue-project
    npm install
    npm run build
    dir
  displayName: "Install deps & build Vue app"

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'vue-project/dist'
    artifact: 'vue-dist'
    publishLocation: 'pipeline'
  displayName: "Publish Vue dist folder"